### PR TITLE
Move to initial_diameter for neurites

### LINKED ISSUE #23: neurite properties have no diameter
Hi,

It seems both axon and dendrite type neurites' properties have no diameter !

Or are  ``axon_diameter`` and ``dendrite_diameter`` properties of a neuron ?

Confusing. Anyway, here what makes me believe axons and dendrites have no diameters :

With ``neuron`` created by  ``create_neurons()``

    ds.set_neurite_properties(neuron,neuron.dendrites["dendrite_1"],
                              params={ "dendrite_diameter": 3. * um})                                                                                                                            

one gets

	KeyError                                  Traceback (most recent call last)
	<ipython-input-20-f4ea6ce20f95> in <module>
	----> 1 ds.set_neurite_properties(neuron,neuron.dendrites["dendrite_1"],params={ "dendrite_diameter": 3. * um})

	_pygrowth.pyx in dense._pygrowth.set_neurite_properties()

	_pygrowth.pyx in dense._pygrowth._check_params()
	KeyError: "Unknown parameter 'dendrite_diameter' for `neurite`."


```python
In [3]: neuron = ds.create_neurons(params={"position": (0., 0.)*um}, num_neurites=0)                                                                                        
In [4]: neuron.create_neurites(num_neurites=1,neurite_types="axon")                 
In [5]: neuron.create_neurites(num_neurites=1,neurite_types="dendrite")                                                                                                                                 
In [6]: neuron.neurites                                                                                                                                                                                                                   
In [7]: dd=neuron.dendrites                                                                                                                                                                                                               
In [8]: dd                                                                                                                                                                                                                                  
Out[8]: { 'dendrite_1': Neurite<dendrite_1 of neuron 0> }

In [9]: d1=dd["dendrite_1"]                                                                                                                                                                                                                
zero-dimensional arrays cannot be concatenated
dendrite.xy: dendrite_1 missing

In [10]: d1.get_properties()                                                                                                                                                                                                                
Out[10]:
{
  'critical_pull'                          : 4.0,
  'affinity_dendrite_soma_other_neuron'    : 0.0,
  'affinity_dendrite_soma_same_neuron'     : nan,
  'affinity_dendrite_axon_same_neuron'     : nan,
  'affinity_dendrite_dendrite_same_neuron' : nan,
  'duration_of_retraction'                 : 4.0 minute,
  'proba_down_move'                        : 0.008,
  'sensing_angle'                          : 69.99825383113267 degree,
  'taper_rate'                             : 0.002,
  'retraction_probability'                 : 0.001,
  'filopodia_min_number'                   : 24,
  'observables'                            : [
                                               'angle',
                                               'length',
                                               'num_growth_cones',
                                               'num_tumbles',
                                               'retraction_time',
                                               'speed',
                                               'status',
                                               'stepping_probability'
                                             ],
  'neurite_type'                           : 'dendrite',
  'filopodia_wall_affinity'                : 2.0,
  'diameter_fraction_lb'                   : 0.8,
  'persistence_length'                     : 500.0 micrometer,
  'diameter_ratio_avg'                     : 1.0,
  'use_van_pelt'                           : False,
  'gc_split_angle_mean'                    : 97.95031817647606 degree,
  'max_sensing_angle'                      : 89.95437383553924 degree,
  'max_gc_number'                          : 500,
  'diameter_ratio_std'                     : 0.02,
  'gc_split_angle_std'                     : 9.994930426171027 degree,
  'affinity_dendrite_axon_other_neuron'    : 5.0,
  'lateral_branching_angle_std'            : 0.9994930426171028 degree,
  'affinity_dendrite_self'                 : nan,
  'lateral_branching_angle_mean'           : 59.969582557026165 degree,
  'max_arbor_length'                       : 5000.0 micrometer,
  'active'                                 : True,
  'diameter_eta_exp'                       : 2.67,
  'speed_decay_factor'                     : 0.0,
  'min_branching_distance'                 : 20.0 micrometer,
  'use_uniform_branching'                  : False,
  'use_flpl_branching'                     : False,
  'speed_growth_cone'                      : 0.05 micrometer / minute,
  'use_uniform_split'                      : False,
  'scale_up_move'                          : 20.0 micrometer,
  'growth_cone_model'                      : 'constant_pull-only_run-and-tumble',
  'affinity_dendrite_dendrite_other_neuron': 2.0,
  'filopodia_finger_length'                : 12.0 micrometer
}
```
**no dendrite_diameter above**

### PR DESCRIPTION
**Pull request by Silmathoron**
Fixes #23 by moving diameter to neurite level,introducing new ``"initial_diameter"`` keyword instead of previous ``"axon_diameter"`` and ``"dendrite_diameter"`` at neuron level.
This enables custom diameter for each neurite.

### CODE REVIEW

**Comment by SBottani** [comment]
Hi Tanguy,
I am updating the "updated" examples on my fork. 
I just wanted to mention a small issue, due to the change on the initialization of diameters.

Now when _updating_ the parameters with dense.set_object_properties() we must remove the initial_parameter in the parameter dicttionary given as argument.

**Comment by Silmathoron** [comment]
@SBottani I think this is quite logical and I'm not sure I see the need for change: why would you reuse a dictionary with the same parameters? All it would do is take longer to perform nothing at all...
I think this behavior actually encourages people to do the right thing: only use dictionaries that contain *only* the parameters that are relevant ;)

**Comment by SBottani** [comment]
Yes. It makes sense.

**Comment by Silmathoron** [comment]
@SBottani in that case, can this PR be merged or do you want to perform further checks?
(can you approve it if it's fine?)

**Comment by SBottani** [comment]
Hi Tanguy,
Ok I reviewed the files and already updated most of my examples to run with this branch.
You can proceed with merging it to the master
Hope I'll finish soon on my side all my tasks !
Best
Samuel

**Pull request merged**
